make imgur fail more gracefully
this commit incorporates 2 good suggestions from brbsix's fork:
https://github.com/brbsix/imgur.sh/commit/b312115a5527868887ad7b1f43153b50d4fb7603

diff --git a/imgur b/imgur
--- a/imgur
+++ b/imgur
@@ -47,13 +47,11 @@ clip=""
 errors=false
 
 # Loop through arguments
-while [ $# -gt 0 ]; do
-	file="$1"
-	shift
+for file in "$@"; do
 
-	# Check file exists
-	if [ ! -f "$file" ]; then
-		echo "File '$file' doesn't exist; skipping" >&2
+	# Check file exists and is readable
+	if [ ! -f "$file" ] || [ ! -r "$file" ]; then
+		echo "File '$file' doesn't exist or can't be read; skipping" >&2
 		errors=true
 		continue
 	fi
